import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/app/component/Navbar/Navbar";
import "./globals.css";

const avantgardebookbt = localFont({
  src: [
    {
      path: "./fonts/avantgardebookbt.ttf",
      weight: "400",
    },
    {
      path: "./fonts/avantgardedemibt.ttf",
      weight: "500",
    },
    {
      path: "./fonts/avantgardedemiobliquebt.ttf",
      weight: "700",
    },
  ],
  variable: "--font-avantgardebookbt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avantgardebookbt.variable}   antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
