import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/app/component/Navbar/Navbar";
import "./globals.css";

const avantgardebookbt = localFont({
  src: [
    {
      path: "./fonts/avantgardebookbt.ttf", // Correct path to the regular font
      weight: "400", // Regular weight
    },
    {
      path: "./fonts/avantgardedemibt.ttf", // Correct path to the medium font
      weight: "500", // Medium weight
    },
    {
      path: "./fonts/avantgardedemiobliquebt.ttf", // Correct path to the bold font
      weight: "700", // Bold weight
    },
  ],
  variable: "--font-avantgardebookbt", // CSS variable for global use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avantgardebookbt.variable}   antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
